global using BotAssistant.Infrastructure.Options;
global using BotAssistant.Infrastructure.TelegramBot.Options;
global using BotAssistant.Infrastructure.TelegramBot.Services.Interfaces;
global using Microsoft.Extensions.Options;
global using Telegram.Bot;
global using Serilog;
global using Telegram.Bot.Types;
global using Telegram.Bot.Types.InputFiles;
global using File = System.IO.File;
global using BotAssistant.Infrastructure.Speech;
global using Telegram.Bot.Types.Enums;
global using BotAssistant.Infrastructure.TelegramBot.Model;
global using BotAssistant.Infrastructure.TelegramBot.Services.Handlers.Base;
global using BotAssistant.Infrastructure.TelegramBot.Services.Handlers;
global using BotAssistant.Infrastructure.TelegramBot.Services.Handlers.CommandHandler.Interfaces;