global using BotAssistant.Application.Contract.TelegramServices;
global using BotAssistant.Application.Contract.Model.Telegram;
global using BotAssistant.Application.Contract.Model.Telegram.Constants;
global using BotAssistant.Infrastructure.Options;
global using Microsoft.Extensions.Options;
global using Telegram.Bot;
global using Telegram.Bot.Types;
global using Telegram.Bot.Types.Payments;
global using Telegram.Bot.Types.Enums;
global using File = System.IO.File;
global using BotAssistant.Application.Contract;
global using BotAssistant.Application.Contract.Model.Recognize;
global using BotAssistant.Infrastructure.Yandex.Object;
global using BotAssistant.Infrastructure.Yandex.Speech;
global using BotAssistant.Infrastructure.TelegramBot.Extensions;
global using BotAssistant.Infrastructure.Worker.Model;
